### ISSUE TITLE
Maquette

### ISSUE THREAD

**Issue by PierreCIT** [PierreCIT/MyComifClient#1]
[Voici le lien vers la maquette](https://www.figma.com/file/btfw4zjOtyvBfv8JU2HyzD/Maquette-Comif-app)

**Comment by AlexandreLadriere** [comment]
Nouvelle maquette diponible en suivant les indications fournies lors de la réunion, à savoir:
- Mise en page sous forme de tabulation
        - Tab1 pour accueil (Logo Comif + nom utilisateurs + statistiques)
        - Tab2 pour transactions (Transactions avec date + heure + objet + montant)
- Icon paramètres
- Meilleur mise en valeur du montant des transactions

Egalement une retouche des couleurs et fond image bière (en attendant visuel pour fond liquide réactif)

Disponible à: https://www.figma.com/file/btfw4zjOtyvBfv8JU2HyzD/Maquette-Comif-app?node-id=0%3A1
