### ISSUE TITLE
Code client pour récupérer requêtes API (balance, transactions)

### ISSUE THREAD

**Issue by hugoseri** [PierreCIT/MyComifClient#11]

**Comment by jcchevalier** [comment]
The #17 pull request implements user requests to the API and the handling of the server's response. Some updates will be required, as for instance the link between the connexion interface and the HTTP services implemented in the application.

**Comment by jcchevalier** [comment]
I added new routes server-side, that retrieves data from the connected user and only the connected user, as he cannot access to the data of other user. Those routes are:
1. `https://comif.fr/api/users/info`: a `GET` request on this URL retrieves informations about the logged on user. It uses the token to know who is asking.
2. `https://comif.fr/api/transactions/info`: a `GET` request on this URL retrieves informations about the transactions made by the logged on user. It also uses the token to know who is asking.

The issue #29 describes the steps that must be followed by an user to change his password with his actual one.
