### ISSUE TITLE
Prise en main API

### ISSUE THREAD

**Issue by PierreCIT** [PierreCIT/MyComifClient#2]

**Comment by hugoseri** [comment]
[Lien vers le repo de l'API](https://gitlab.com/minitel-army/comif-api/tree/dev).

### Doc API et routes 
La doc est très très légère... Mais en fouillant le code on peut deviner les routes existantes. Les routes en GET qui semblent exister et qui nous seront utiles : 
* ```transactions/by-user/{userId}``` pour obtenir les transactions faites pour chaque client (contient la date de la transaction, sa valeur, l'id des produits achetés...),
* ```products``` pour obtenir la liste des produits (et les détails associés: nom, prix...).

### Restriction d'accès à l'API
J'ai tenté de faire ces requêtes sans succès, j'ai un ```unauthorized```.
Il y a sûrement un système d'authentification ou mdp à fournir dans la requête, j'ai tenté avec les id de la comif mais ça a pas fonctionné. A voir avec Valentin s'il en sait plus.    

Après mes tentatives à l'arrache, j'ai vu que la doc de l'API renseigne ça :    

![image](https://user-images.githubusercontent.com/23211880/68572802-a0d96b00-0466-11ea-9873-aa9e0f5ca7dd.png)

En regardant un peu, ça correspond à une forme d'authentifcation pour pouvoir accéder à une API. Faudrait voir avec Valentin s'il a des identifiants/méthodes pour pouvoir utiliser ça.

**Comment by jcchevalier** [comment]
After some research, this is what I found:

1. Authentification

- The authentication route is `https://comif.fr/api/users/login`. You need to use a POST method, which contains the following JSON: `{"client_id":1, "client_secret":"secret", "grant_type":"password", "username":"USERNAME", "password":"PASSWORD"}`. I still do not know what is the role of the firsts three champs.
- After the verification of the credentials sent by the user, the server returns another JSON: `{
    "token_type": "Bearer", "expires_in": 7948800, "access_token": "ACCESS_TOKEN", "refresh_token": "REFRESH_TOKEN" }`. The first argument of this JSON specifies that the type of token is a Bearer token. Then you have the durability of this token, and finally the access token. The use of this token is to authenticate each request made by the user, and assure that he has enough permissions to do this. The utility of the fourth argument is still unknown.

2. Retrieve an user's data

- The route to get the data from a specific user is `https://comif.fr/api/users/{userId}`. There, you use a GET method. The server returns a JSON (if the user is authenticated), which contains several data about the user.

3. Retrieve the last transactions made by an user
 
- The route to get the data from a specific user is `https://comif.fr/api/transactions/by-user/{userId}`. The server returns a JSON containing the last 20 transactions made by this user.

**Comment by jcchevalier** [comment]
I forgot to mention it but the backend of the server is coded in PHP, with the LARAVEL's framework.
