### ISSUE TITLE
Managing first connexion email check

### ISSUE THREAD

**Issue by hugoseri** [PierreCIT/MyComifClient#23]
For now, you directly get a pop-up message saying an email was sent to the email adress given, even if the field is empty or doesn't contain a regular email string.
We should check the string to verify it's in an email.    
I also think we shouldn't communicate whether the email given exists or not to avoid telling information about database to people.    
What I suggest then is to : 
* check if the field corresponds to an email string (I think there are all made functions to check that, at least it exists in PHP),
* put a neutral popup if the string is valid with something like `If this is an authorized email, you will receive your password. Check your emails !`.

**Comment by jcchevalier** [comment]
I think we must merge this functionality with a `Forgotten password` one, as they have the same end and the same way of processing: user sends a request to the server, which sends back a mail that contain a link that allow the user to define a new password. This password will then be hashed and put into the database.
