### ISSUE TITLE
User must be able to change his password

### ISSUE THREAD

**Issue by jcchevalier** [PierreCIT/MyComifClient#29]
We must implement a new fragment/activity that allows the user to change his password (with one field which must be filled in with his old password, and 2 with his new one). Then those data must be transmitted after the user clicks on a button, and disconnect the said-user from the application, so he must reconnect with his new password.

**Comment by jcchevalier** [comment]
The API request is the following one:
URL: `https://comif.fr/api/users/reset`
Method: POST
Body: `
{
	"old_password": "1234",
	"new_password": "6789",
	"verified_new_password": "6789"
}
`

**Comment by hugoseri** [comment]
I've developed the reset password page on the comif website. I'm waiting for more infos about what to send and where. @jcchevalier
