### ISSUE TITLE
Effet liquide bière

### ISSUE THREAD

**Issue by PierreCIT** [PierreCIT/MyComifClient#3]
[Lien vers une librairie](https://google.github.io/liquidfun/?fbclid=IwAR2GTiy-0eRdfUVRwp14d7VPPVfs4GZyWgDH8rUdK1lxylmMwTaAfngrSbY)

**Comment by jcchevalier** [comment]
After an internet research about this library, I realized that this library is a C++ one. The use of it in this project will be more difficult as we originally thought, as this is something we never did. I will keep doing researches, as the rest of the application progresses well. I'll also ask Gaëtan Maisse about this on Monday 18th.

**Comment by jcchevalier** [comment]
I think that for the first release, this functionality is not necessary.
