### ISSUE TITLE
Last design issues

### ISSUE THREAD

**Issue by hugoseri** [PierreCIT/MyComifClient#33]
Based on 9/01/2020 meeting, here are he last design issues to fix :
- [x] French text (string_fr file)
- [x] Background gradient
- [x] Stats values design (lines)
- [x] Font color in infos page
- [x] Back button in first connection/change password pages
- [x] App name (My Comif)

**Comment by AlexandreLadriere** [comment]
I have decided not to change the stats value design (lines) as in french it is not a problem (and almost all users will use the app in french)
