### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by hugoseri** [PierreCIT/MyComifClient#34]
Last refactoring steps based on 9/01/2020 meeting:

- [ ] Comments
- [ ] Use inheritance
- [ ] Close app when not connected to network

**Comment by AlexandreLadriere** [comment]
A new branch named "documentation" was created. Javadoc style is used for all functions, even ```private``` ones, but ```override``` functions are not commented.

**Comment by AlexandreLadriere** [comment]
All kotlin files are commented, except for ```UnsafeHTTPClient.kt``` and ```HTTPServices.kt```. @jcchevalier is the best person for commenting them.

**Comment by AlexandreLadriere** [comment]
The documentation branch was merged even if the ```UnsafeHTTPClient.kt``` and ```HTTPServices.kt``` files are still not commented. @jcchevalier need to document them.
