### ISSUE TITLE
Balance Update not working

### ISSUE THREAD

**Issue by AlexandreLadriere** [PierreCIT/MyComifClient#39]
A beta tester told me that after having a beer at the Comif, his account balance didn't update. However, the statistic of the day did update and the purchase appears in the shopping list. 

He was able to reproduce this error a second time in the evening.

**Comment by hugoseri** [comment]
@AlexandreLadriere i think we are confronting a very specific scélérat situation man !

**Comment by jcchevalier** [comment]
@AlexandreLadriere, an implementation that solves this bug has been proposed in the pull request #42. Please check out !

**Comment by AlexandreLadriere** [comment]
I am aware of this pull request and the branch will be merged after the beta users feedbacks during the next Tibbar (27.02.2020) for instance.

**Comment by jcchevalier** [comment]
I did huge modifications of the code inside this branch, so be sure to uninstall completely the application  before testing it, so you will start on a brand new version without the database (which structure changed too)
