### ISSUE TITLE
Dev front-end (fragments, images...)

### ISSUE THREAD

**Issue by PierreCIT** [PierreCIT/MyComifClient#4]
Développement du front en suivant la maquette préalablement élaborée [ici](https://www.figma.com/file/btfw4zjOtyvBfv8JU2HyzD/Maquette-Comif-app?node-id=0%3A1).

**Comment by AlexandreLadriere** [comment]
To do:
- [ x ]  Create TabLayout with 2 tabs
- [ x ] Create HomeFragment and TransactionFragment
- [ x ] Create colors.xml with colors used for the UI design
- [ ] Create menu with Settings Button
- [ ] Create Settings Activity
- [ ] Create RecyclerView in TransactionFragment (with all files associated)
- [ ] Create HomeFragment UI

**Comment by AlexandreLadriere** [comment]
For the moment, a Transaction object with the following attributes has been created:

`data class Transaction(
    val date: String,
    val hour: String,
    val product: MutableMap<String, Int>,
    val price: String
) : Serializable`

It may be necessary to review the type of some attributes according to the data retrieved from the Comif API (and modify the RecyclerView files of the TransactionFragment accordingly to that)

**Comment by AlexandreLadriere** [comment]
The UI for HomeFragment has been created. There are still some details to be reviewed (in particular the drooling aspect of the logo, or the addition of the "offline" bar)

It would be nice to make a presentation to the other members of the group to get their feedback

**Comment by AlexandreLadriere** [comment]
Pull request created to merge this branch to the Dev branch
