### ISSUE TITLE
Page de connexion

### ISSUE THREAD

**Issue by hugoseri** [PierreCIT/MyComifClient#6]
1e page de connexion avec :
* champ email,
* champ mdp,
* bouton connexion,
* bouton 1e connexion.

2e page pour la 1e connexion avec : 
* champ email.

**Comment by AlexandreLadriere** [comment]
Two activities were created. 

The first one is `ConnexionActivity`, which contains:

- App name
- App Logo (Comif Logo)
- email input field
- password input field
- Connexion button
- First Connexion button

When you click one the "First Connexion Button", you are redirected to the `FirstConnexionActivity`, which contains:

- App name
- App logo (Comif logo)
- email input field
- Get Password button

When you click on the "Get password Button", a pop-up is displayed to indicate that the password was sent by email. Closing this pop-up will redirect you to the `ConnexionActivity`
