### ISSUE TITLE
Modif accueil avec menu burger 

### ISSUE THREAD

**Issue by hugoseri** [PierreCIT/MyComifClient#7]
Ajout d'un menu burger avec :
* Déconnexion,
* Infos.

**Comment by AlexandreLadriere** [comment]
A branch, called `burger_menu_creation` was created to add a burger menu with a Navigation Drawer. However, upon reflection, it appears that the updating of a Navigation Drawer in our application does not add value and does not satisfy the constraints of material design.

It was decided to add the different options in the existing menu. (Three-point menu).

The name of this branch is therefore misleading.

**Comment by AlexandreLadriere** [comment]
The pull request to merge is done
