### ISSUE TITLE
Add & configure new routes to the API

### ISSUE THREAD

**Issue by hugoseri** [PierreCIT/MyComifClient#8]
La route update password existe mais elle ne fait rien. Il faut définir les fonctions pour modifier le mdp dans la BDD.

**Comment by jcchevalier** [comment]
We need to add those routes to the API:

1. One `GET` request, which will allow user to get information about his own account. This one is urgent, as for now the only way to get any information about the user is by specifying the user's ID, which is only stocked inside the server-side database. The user cannot retrieve this ID, and it is better that he does not.

2. One `POST` request, which will allow the user to change his password, or to set one if he has not already
